### ISSUE TITLE
Why do I need to start a new goroutine

### ISSUE THREAD

**Issue by zhaozhao** [golang-book/bootcamp-examples#3]
I'm watching your bootcamp course at youtube.
One thing really confuses me is why I need to start a new goroutine to send message to the channel in [chat-server](https://github.com/golang-book/bootcamp-examples/blob/master/week2/day2/chat-server/main.go#L33) example.

I tried to send the message in the `Run` function. The chat sever indeed seems to not function any more.  I still can't figure out why after google for this.

Any detailed specification or explanation about this?

**Comment by ZacharyJacobCollins** [comment]
If i remember correctly, when i went through that example, the chat server code didnt actually work.  

Try this example out in order to understand them a bit better https://www.golang-book.com/books/intro/10 .

  Essentially a go routine is used in order to spin up a thread of a function.  

If you wanted code for a working chat example I actually am working on one, and can share the repo if you'd like

**Comment by zhaozhao** [comment]
Thanks for reply. @ZacharyJacobCollins 
The video related to the code is at [youtube](https://www.youtube.com/watch?v=cNxfgXrHeAg&list=PLSak_q1UXfPrI6D67NF8ajfeJ6f7MH83S&index=74). Round 14:00 in that video, calebdoxsey explained that a little bit.
The code in this repo works fine for me. But when I remove the lines(Line 33, 41) which start a new go routine to send the join/leave message like this:
```
func (cs *ChatServer) Run() {
	for {
		select {
		case user := <-cs.Join:
			cs.Users[user.Name] = user

			cs.Input <- Message{
				Username: "SYSTEM",
				Text:     fmt.Sprintf("%s joined", user.Name),
			}

		case user := <-cs.Leave:
			delete(cs.Users, user.Name)

			cs.Input <- Message{
				Username: "SYSTEM",
				Text:     fmt.Sprintf("%s left", user.Name),
			}

		case msg := <-cs.Input:
			for _, user := range cs.Users {
				select {
				case user.Output <- msg:
				default:
				}
			}
		}
	}
}
```
It's no longer functioning.
[Chapter 10](https://www.golang-book.com/books/intro/10) can't explain this.

**Comment by calebdoxsey** [comment]
Hi @zhaozhao , so the reason you need to send in a goroutine, is that the thing reading the goroutine is in the same for loop:

    	case msg := <-cs.Input:
			for _, user := range cs.Users {
				select {
				case user.Output <- msg:
				default:
				}
			}
		}

And the `Input` channel was created without a size:

    Input: make(chan Message)

When created without a size, channels are synchronous. This means a send will only succeed if there is a corresponding receive on the other side of the channel. Until then the goroutine will block.

So that's what's happening here. Sending to `cs.Input` can't succeed because the receive is done in the same loop.

Another way to (partially) prevent this is to give the channel a capacity when you create it:

    Input: make(chan Message, 1)

Now the channel would have a buffer and the initial send could succeed, loop around one more time, get to the select, and choose the message it just put on `cs.Input`.

Unfortunately it is still possible to deadlock in this scenario if two users were to join/leave at the same time and the select loop chose that branch (rather than the input branch) twice in a row. (When multiple branches of a select statement could possibly succeed simultaneously, it will randomly choose one of them) Although the first send would still succeed, the second send would block as the capacity would've been reached.

Increasing the capacity further would make the issue less and less likely, but the safest approach would be to send in a goroutine.

This block of code:

			go func() {
				cs.Input <- Message{
					Username: "SYSTEM",
					Text:     fmt.Sprintf("%s joined", user.Name),
				}
			}()

Is a good candidate to be pulled out into a function:

	func (cs *ChatServer) send(username, text string) {
		go func() {
			cs.Input <- Message{
				Username: username,
				Text:     text,
			}
		}()
	}

And then:

			cs.send("SYSTEM", fmt.Sprintf("%s joined", user.Name))

**Comment by zhaozhao** [comment]
That's exactly what I'm looking for. Thanks @calebdoxsey .
